import { Theme } from "../styling.slint";
import { Container, SideButton, InputField, OverviewCard, BaloButton,Clock,CircularProgress, RectangularProgress} from "../components.slint";
import {
    Button, ComboBox, LineEdit,
    VerticalBox, HorizontalBox, GridBox, ListView, ProgressIndicator, 
} from "std-widgets.slint";

import {Database,Impressoras,Estoque-Database} from "../shared.slint";
 

export component dashboard_screen {
    in-out property <[Database]> clients_database;
    in-out property <Database> selected_client;
    in-out property <[Estoque-Database]> estoque_database;
    in-out property <float> vendas_total;
    in-out property <string> temp_data;
    in-out property <int> filamento-total;

    in-out property <string> time;
    callback calcular_preco();
    callback registrar_cliente();
    callback registrar_impressora();
    callback registrar_estoque();
    callback pedidos();
    callback impressoras();
    callback configuracoes();
    callback estoque();
    VerticalLayout {
        width: parent.width;
        height: parent.height;
        
        HorizontalLayout {
            padding: Theme.spacing;
            spacing: Theme.spacing;
            Text {
                text: "Dashboard";
                color: Theme.onBackground;
                font-weight: 800;
                font-size: 40px;
            }

            HorizontalLayout {
                height: 10px;
                alignment: end;
                
            }
        }

        GridBox {
            Row {
                Rectangle {
                    background: Theme.background;
                    GridBox {
                        spacing: Theme.spacing;
                        padding: Theme.spacing;
                        Row {
                            Container {
                            
                                VerticalBox {
                                    Text {
                                        text: "Pedidos";
                                        color: Theme.onSurface;
                                        font-weight: 800;
                                        font-size: Theme.fontSizeTitle;
                                        horizontal-alignment: center;
                                    }

                                    Text {
                                        text: "\{root.clients_database.length}";
                                        color:  Theme.onSurface;
                                        horizontal-alignment: center;
                                        font-weight: 700;
                                        font-size: Theme.fontSizeTitle;
                                    }
                                }
                            }

                            Container {
                                
                                VerticalBox {
                                    Text {
                                        horizontal-alignment: center;
                                        text: "Resumo de Vendas";
                                        color:   Theme.onSurface;
                                        
                                        font-weight: 800;
                                        font-size: 16px;
                                    }

                                    HorizontalBox {
                                        Text {
                                            text: "Vendas no mês:";
                                            color:   Theme.onSurface;
                                            font-weight: 500;
                                            font-size: 13px;
                                        }

                                        Text {
                                            horizontal-alignment: right;
                                            text: "0";
                                            color:  Theme.onSurface;
                                            font-weight: 500;
                                            font-size: 13px;
                                        }
                                    }

                                    HorizontalBox {
                                        Text {
                                            text: "Faturamento:";
                                            color:  Theme.onSurface;
                                            font-weight: 500;
                                            font-size: 13px;
                                        }

                                        Text {
                                            horizontal-alignment: right;
                                            text: "R$" + vendas_total.to-fixed(2);
                                            color:  Theme.onSurface;
                                            font-weight: 500;
                                            font-size: 13px;
                                        }
                                    }
                                }
                            }

                            Container {
                                width: 20%;
                               
                                VerticalBox {
                                    alignment: start;
                                    spacing: Theme.spacing;
                                    Text {
                                        padding: Theme.spacing;
                                        text: "Filamento";
                                        color:   Theme.onSurface;
                                        font-weight: 800;
                                        font-size: 16px;
                                        vertical-alignment: center;
                                        horizontal-alignment: center;
                                    }

                                    HorizontalBox {
                                        alignment: center;
                                        CircularProgress {
                                            width: 100px;
                                            background-color: Theme.onPrimary;
                                            progress-color: Theme.secondaryLight;
                                            text-color:  Theme.onSurface;
                                            height: 100px;
                                            padding: Theme.spacing;
                                            progress: ((filamento-total / 10000) * 10);
                                        }
                                    }
                                }
                            }
                        }

                      
                    }
                }
            }

            HorizontalLayout {
                height: 500px;
                spacing: Theme.spacing;
                padding: Theme.spacing;
                Container {
                    width: 50%;
                   
                    VerticalBox {
                         
                        Text {
                            horizontal-alignment: center;
                            padding: Theme.spacing;
                            text: "Estoque";
                            color:  Theme.onSurface;
                            font-weight: 800;
                            font-size: 16px;
                        }

                       

                        ListView {
                            horizontal-scrollbar-policy: as-needed;
                            for item in estoque_database: Rectangle {
                                max-height: 30px;

                               
                               
                                HorizontalBox {
                                    Rectangle {
                                        VerticalBox {
                                            Text {
                                            text: item.material + ": ";
                                            padding: Theme.spacing;
                                            color: Theme.onSurface;
                                            font-weight: 600;
                                            font-size: 15px;
                                            }

                                            
                                        }
                                        
                                        width: 20%;
                                        
                                    }
                                

                                    VerticalBox {
                                        alignment: center;
                                          RectangularProgress {
                                        width: 50%;
                                        progress: (item.quantidade.to-float()/ item.quantidade-total);
                                        
                                    
                                    }
                                     
                                    }
                                   

                                   

                                    Rectangle {
                                        width: 20%;
                                        Text {
                                            
                                            text: item.quantidade + "/" + item.quantidade-total + item.medida;
                                            color: Theme.onSurface;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                Container {
                    
                     
                    VerticalBox {
                        spacing: Theme.spacing;
                        padding: Theme.spacing;
                        Text {
                            horizontal-alignment: center;
                             padding: Theme.spacing;
                            text: "Historico de Pedidos";
                            color:  Theme.onSurface;
                            font-weight: 800;
                            font-size: 16px;
                        }
                 
                     
                    HorizontalBox {
                         spacing: Theme.spacing;
                        padding: Theme.spacing;
                     
                          Text {
                            text: "Nome";
                            color:   Theme.onSurface;
                            font-weight: 700;
                            horizontal-alignment: center;
                        }

                        Text {
                            text: "Preço";
                            color:   Theme.onSurface;
                            font-weight: 700;
                            horizontal-alignment: center;
                        }

                        Text {
                            text: "Status";
                            color:   Theme.onSurface;
                            font-weight: 700;
                            horizontal-alignment: center;
                        }
                    }

                    ListView {
                        
                    padding: Theme.spacing;
                        height: 99%;
                        for client[index] in clients_database: TouchArea {
                            clicked => {
                                root.selected_client = root.clients_database[index];
                                pedidos();
                            }
                          property <bool> selected_hover <=> self.has-hover;
                          padding: Theme.spacing;
                          Rectangle {
                            
                                height: 90%;
                                padding: 8px;
                      
                              background: !selected_hover? Theme.background:Theme.secondaryLight;
                                HorizontalBox {
                                    alignment: center;
                                    Rectangle {
                                        width: 30%;
                                        Text {
                                            text: client.nome;
                                            color:  Theme.onSurface;
                                            horizontal-alignment: center;
                                            overflow: elide;
                                        }
                                    }

                                    Rectangle {
                                        width: 30%;
                                        Text {
                                            text: client.preco + "R$";
                                            color: Theme.onSurface;
                                            horizontal-alignment: center;
                                        }
                                    }

                                    Rectangle {
                                        width: 30%;
                                        Text {
                                            text: client.status;
                                            color: Theme.onSurface;
                                            horizontal-alignment: center;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                }
            }
        }
    }
}
