import { Theme } from "../styling.slint";
import { Container, SideButton, InputField, OverviewCard} from "../components.slint";
import {
    Button, ComboBox, LineEdit,
    VerticalBox, HorizontalBox, GridBox, ListView
} from "std-widgets.slint";

import {Database,Impressoras,Estoque-Database} from "../shared.slint";
 

export component dashboard_screen {
    in-out property <[Database]> clients_database;
    in-out property <Database> selected_client;
    in-out property <[Estoque-Database]> estoque_database;
    in-out property <float> vendas_total;
    in-out property <string> temp_data;
    callback calcular_preco();
    callback registrar_cliente();
    callback registrar_impressora();
    callback registrar_estoque();

    
    callback pedidos();
    VerticalBox {
    //  height: 700px;
    //  width: 900px;
    visible: true;
    // spacing: Theme.spacing;

    HorizontalBox {
        // spacing: Theme.spacing;

        VerticalBox {
            // spacing: Theme.spacing;

            HorizontalBox {
                // max-height: 50px;
                Text {
                        text: "Dashboard";
                        color: black;
                        font-weight: 800;
                        font-size: 40px;
                    }

                    SideButton {
                        texto: "Pedidos";
                         
                    }

                    SideButton {
                        texto: "Clientes";
                    }

                    SideButton {
                        texto: "Estoque";
                    }

                    SideButton {
                        texto: "Impressoras";
                    }

                    SideButton {
                        texto: "Modelos";
                    }

                    SideButton {
                        texto: "Financeiro";
                    }
                }

                GridBox {
                // spacing: Theme.spacing;
 

                Row {
                        HorizontalBox {
                        // spacing: Theme.spacing;

                        VerticalBox {
                            // spacing: Theme.spacing;

                            HorizontalBox {
                                // spacing: Theme.spacing;

                                Container {
                                        cor: white;
                                        VerticalBox {
                                            Text {
                                                text: "Pedidos";
                                                color: black;
                                                font-weight: 800;
                                                font-size: 20px;
                                                horizontal-alignment: center;
                                            }

                                            Text {
                                                text: "\{root.clients_database.length}";
                                                color: black;
                                                horizontal-alignment: center;
                                                font-weight: 700;
                                                font-size: 20px;
                                            }
                                        }
                                    }

                                    Container {
                                        cor: white;
                                        VerticalBox {
                                            Text {
                                                horizontal-alignment: center;
                                                text: "Resumo de Vendas";
                                                color: black;
                                                font-weight: 800;
                                                font-size: 20px;
                                            }

                                            HorizontalBox {
                                                Text {
                                                    text: "Vendas no mês:";
                                                    color: black;
                                                    font-weight: 500;
                                                    font-size: 15px;
                                                }

                                                Text {
                                                    horizontal-alignment: right;
                                                    text: "0";
                                                    color: black;
                                                    font-weight: 500;
                                                    font-size: 15px;
                                                }
                                            }

                                            HorizontalBox {
                                                Text {
                                                    text: "Faturamento:";
                                                    color: black;
                                                    font-weight: 500;
                                                    font-size: 15px;
                                                }

                                                Text {
                                                    horizontal-alignment: right;
                                                    text: "R$" + vendas_total.to-fixed(2);
                                                    color: black;
                                                    font-weight: 500;
                                                    font-size: 15px;
                                                }
                                            }
                                        }
                                    }
                                }

                                Container {
                                    cor: white;
                                    GridBox {
                                        Row {
                                            Container {
                                                cor: white;
                                               
                                            }

                                            Container {
                                                cor: white;
                                            }
                                        }

                                        Row {
                                            Container {
                                                cor: white;
                                            }

                                            Container {
                                                cor: white;
                                            }
                                        }
                                    }
                                }
                            }
                        }

                        VerticalBox {
                        // spacing: Theme.spacing;

                        HorizontalBox {
                            // spacing: Theme.spacing;

                            Container {
                                    cor: white;
                                    VerticalBox {
                                    // spacing: Theme.spacing;

                                    HorizontalBox {
                                        // spacing: Theme.spacing;
                                        Text {
                                                text: "Nome";
                                                color: black;
                                                font-weight: 700;
                                                horizontal-alignment: center;
                                            }

                                            Text {
                                                text: "Preço";
                                                color: black;
                                                font-weight: 700;
                                                horizontal-alignment: center;
                                            }

                                            Text {
                                                text: "Status";
                                                color: black;
                                                font-weight: 700;
                                                horizontal-alignment: center;
                                            }
                                        }

                                        ListView {
                                            height: 85%;
                                            for client[index] in clients_database: TouchArea {
                                                clicked => {
                                                    root.selected_client = root.clients_database[index];
                                                    pedidos();
                                                }
                                            // spacing: Theme.spacing;
                                            // padding: Theme.spacing;
                                            Rectangle {
                                                    height: 90%;
                                                    padding: 8px;
                                                // border-radius: 5px;
                                                // drop-shadow-offset-y: 1px;  
                                                background: rgba(0.5,0,1,0.3);
                                                    HorizontalBox {
                                                        alignment: center;
                                                        Rectangle {
                                                            width: 25%;
                                                            Text {
                                                                text: client.nome;
                                                                color: black;
                                                                horizontal-alignment: center;
                                                                overflow: elide;
                                                            }
                                                        }

                                                        Rectangle {
                                                            width: 25%;
                                                            Text {
                                                                text: "R$" + client.preco.to-fixed(2);
                                                                color: black;
                                                                horizontal-alignment: center;
                                                            }
                                                        }

                                                        Rectangle {
                                                            width: 25%;
                                                            Text {
                                                                text: client.status;
                                                                color: black;
                                                                horizontal-alignment: center;
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
