import { Theme } from "../styling.slint";
import { Container, SideButton, InputField, OverviewCard, BaloButton,Clock,CircularProgress} from "../components.slint";
import {
    Button, ComboBox, LineEdit,
    VerticalBox, HorizontalBox, GridBox, ListView, ProgressIndicator, 
} from "std-widgets.slint";

import {Database,Impressoras,Estoque-Database} from "../shared.slint";
 

export component dashboard_screen {
    in-out property <[Database]> clients_database;
    in-out property <Database> selected_client;
    in-out property <[Estoque-Database]> estoque_database;
    in-out property <float> vendas_total;
    in-out property <string> temp_data;
    in-out property <int> filamento-total;

    in-out property <string> time;
    callback calcular_preco();
    callback registrar_cliente();
    callback registrar_impressora();
    callback registrar_estoque();
    callback pedidos();
    callback impressoras();
    callback configuracoes();
    callback estoque();
    VerticalLayout {
        width: parent.width;
        height: parent.height;
        HorizontalLayout {
            padding: Theme.spacing;
            spacing: Theme.spacing;
            Text {
                text: "Dashboard";
                color: black;
                font-weight: 800;
                font-size: 40px;
            }

            HorizontalLayout {
                height: 10px;
                alignment: end;
                
            }
        }

        GridBox {
            Row {
                Rectangle {
                    background: white;
                    GridBox {
                        spacing: Theme.spacing;
                        padding: Theme.spacing;
                        Row {
                            Container {
                                cor: white;
                                VerticalBox {
                                    Text {
                                        text: "Pedidos";
                                        color: black;
                                        font-weight: 800;
                                        font-size: 16px;
                                        horizontal-alignment: center;
                                    }

                                    Text {
                                        text: "\{root.clients_database.length}";
                                        color: black;
                                        horizontal-alignment: center;
                                        font-weight: 700;
                                        font-size: 16px;
                                    }
                                }
                            }

                            Container {
                                cor: white;
                                VerticalBox {
                                    Text {
                                        horizontal-alignment: center;
                                        text: "Resumo de Vendas";
                                        color: black;
                                        font-weight: 800;
                                        font-size: 16px;
                                    }

                                    HorizontalBox {
                                        Text {
                                            text: "Vendas no mês:";
                                            color: black;
                                            font-weight: 500;
                                            font-size: 13px;
                                        }

                                        Text {
                                            horizontal-alignment: right;
                                            text: "0";
                                            color: black;
                                            font-weight: 500;
                                            font-size: 13px;
                                        }
                                    }

                                    HorizontalBox {
                                        Text {
                                            text: "Faturamento:";
                                            color: black;
                                            font-weight: 500;
                                            font-size: 13px;
                                        }

                                        Text {
                                            horizontal-alignment: right;
                                            text: "R$" + vendas_total.to-fixed(2);
                                            color: black;
                                            font-weight: 500;
                                            font-size: 13px;
                                        }
                                    }
                                }
                            }

                            Container {
                                width: 20%;
                                cor: white;
                                VerticalLayout {
                                    alignment: start;
                                    spacing: Theme.spacing;
                                    Text {
                                        padding: Theme.spacing;
                                        text: "Filamento";
                                        color: black;
                                        font-weight: 800;
                                        font-size: 16px;
                                        horizontal-alignment: center;
                                    }

                                    HorizontalBox {
                                        alignment: center;
                                        CircularProgress {
                                            width: 100px;
                                            height: 100px;
                                            padding: Theme.spacing;
                                            progress: ((filamento-total / 10000) * 10).to-fixed(2));
                                        }
                                    }
                                }
                            }
                        }

                      
                    }
                }
            }

            HorizontalLayout {
                height: 500px;
                spacing: Theme.spacing;
                padding: Theme.spacing;
                Container {
                    width: 50%;
                    cor: white;
                    VerticalBox {
                        Text {
                            horizontal-alignment: center;
                            padding: Theme.spacing;
                            text: "Estoque";
                            color: black;
                            font-weight: 800;
                            font-size: 16px;
                        }

                        ListView {
                            for item in estoque_database: Rectangle {
                                max-height: 30px;
                                HorizontalBox {
                                    Rectangle {
                                        width: 20%;
                                        Text {
                                            text: item.material + ": ";
                                            padding: Theme.spacing;
                                            color: black;
                                            font-weight: 600;
                                            font-size: 15px;
                                        }
                                    }

                                    ProgressIndicator {
                                        width: 50%;
                                        progress: (item.quantidade.to-float() / item.quantidade-total);
                                    }

                                    Rectangle {
                                        width: 20%;
                                        Text {
                                            
                                            text: item.quantidade + "/" + item.quantidade-total;
                                            color: black;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }

                Container {
                    
                     cor: white;
                    VerticalBox {
                        spacing: Theme.spacing;
                        padding: Theme.spacing;
                        Text {
                            horizontal-alignment: center;
                             padding: Theme.spacing;
                            text: "Pedidos";
                            color: black;
                            font-weight: 800;
                            font-size: 16px;
                        }
                    
                    // height: 560px;
                     
                    HorizontalBox {
                         spacing: Theme.spacing;
                        padding: Theme.spacing;
                          // spacing: Theme.spacing;
                          Text {
                            text: "Nome";
                            color: black;
                            font-weight: 700;
                            horizontal-alignment: center;
                        }

                        Text {
                            text: "Preço";
                            color: black;
                            font-weight: 700;
                            horizontal-alignment: center;
                        }

                        Text {
                            text: "Status";
                            color: black;
                            font-weight: 700;
                            horizontal-alignment: center;
                        }
                    }

                    ListView {
                        
                    padding: Theme.spacing;
                        height: 85%;
                        for client[index] in clients_database: TouchArea {
                            clicked => {
                                root.selected_client = root.clients_database[index];
                                pedidos();
                            }
                         
                          padding: Theme.spacing;
                          Rectangle {
                                height: 90%;
                                padding: 8px;
                              // border-radius: 5px;
                              // drop-shadow-offset-y: 1px;  
                              background: rgba(0.5,0,1,0.3);
                                HorizontalBox {
                                    alignment: center;
                                    Rectangle {
                                        width: 30%;
                                        Text {
                                            text: client.nome;
                                            color: black;
                                            horizontal-alignment: center;
                                            overflow: elide;
                                        }
                                    }

                                    Rectangle {
                                        width: 30%;
                                        Text {
                                            text: client.preco;
                                            color: black;
                                            horizontal-alignment: center;
                                        }
                                    }

                                    Rectangle {
                                        width: 30%;
                                        Text {
                                            text: client.status;
                                            color: black;
                                            horizontal-alignment: center;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                }
            }
        }
    }
}
