import { Theme } from "../styling.slint";
import { Container, SideButton, InputField, OverviewCard, BaloButton, CustomComboBox, DataInput} from "../components.slint";
import {Button, ComboBox, LineEdit,VerticalBox, HorizontalBox, GridBox, ListView, ScrollView,DatePickerPopup, AboutSlint} from "std-widgets.slint";

import { Database, Impressoras, Estoque-Database } from "../shared.slint";





export component estoque_screen {
    in-out property <[Estoque-Database]> estoque_database;
    in-out property <string> estoque_material;
    in-out property <string> estoque_quantidade;
    in-out property <string> estoque_quantidade_total;
    in-out property <string> estoque_medida;
    in-out property <string> estoque_material_input;
    in-out property <string> estoque_quantidade_input;
    in-out property <string> estoque_preco_input;
    in-out property <Estoque-Database> selectec_estoque;
    in-out property <int> preco_total_estoque;



    in-out property <string> temp_estoque_material;
    in-out property <string> temp_estoque_quantidade;
    in-out property <string> temp_estoque_quantidade_total;
    in-out property <string> temp_estoque_preco;
    in-out property <string>  temp_estoque_medida;

    callback registrar_estoque();
    callback dashboard();
    callback estoque();
    callback impressoras();
    callback configuracoes();
    callback pedidos();
    callback atualizar_estoque();
    callback estoque_total_preco();
    callback excluir_estoque();
    Rectangle {
        width: parent.width;
        height: parent.height;
        background: Theme.background;
        visible: true;
        Estoques := VerticalBox {
            visible: true;
            HorizontalBox {
                GridBox {
                    HorizontalBox {
                        // max-height: 50px;
                        Text {
                            text: "Estoque";
                            color: Theme.onBackground;
                            font-weight: 800;
                            font-size: 40px;
                        }

                        

                        BaloButton {
                            visible: false;
                            texto: "Dashboard";
                            clicked => {
                                dashboard()
                            }
                        }

                        BaloButton {
                            visible: false;
                            texto: "Pedidos";
                            clicked => {
                                pedidos()
                            }
                        }

                        BaloButton {
                            visible: false;
                            texto: "Impressoras";
                            clicked => {
                                impressoras()
                            }
                        }

                        BaloButton {
                            visible: false;
                            texto: "Configurações";
                            clicked => {
                                configuracoes()
                            }
                        }
                        BaloButton {
                            
                            texto: "Adicionar Material";
                            clicked => {
                                novo_material.visible = true;
                                Estoques.visible = false;
                            }
                        }
                    }

                    Edit_Estoque_Screen := PopupWindow {
                        width: parent.width;
                        height: parent.height;
                        close-policy: close-on-click-outside;
                        x: parent.width / 2;
                        y: parent.height * 2.5;
                        VerticalLayout {
                            // width: 500px;
                            // height: 500px;
                            Container {
                                width: 100%;
                                height: 100%;
                                shadow_blur: 10px;
                                border_width: 1px;
                                border_radius: 10px;
                                VerticalBox {
                                    HorizontalBox {
                                        Text {
                                            vertical-alignment: center;
                                            text: "Editar Material";
                                            color: Theme.onSurface;
                                            font-weight: 800;
                                            font-size: 20px;
                                        }

                                        BaloButton {
                                            width: 80px;
                                            height: 40px;
                                            texto: "Confirmar";
                                            clicked => {
                                                
                                                atualizar_estoque();
                                                Edit_Estoque_Screen.close();
                                                temp_estoque_material = "";
                                                temp_estoque_quantidade = "";
                                                temp_estoque_quantidade_total = "";
                                                temp_estoque_preco = "";
                                                temp_estoque_medida = "";
 
                                            }
                                        }
                                    }

                                    InputField {
                                        texto: "Material: ";
                                        max_lenght: 40;
                                        input <=> temp_estoque_material;
                                    }

                                    InputField {
                                        texto: "Quantidade: ";
                                        max_lenght: 20;
                                        input <=> temp_estoque_quantidade;
                                    }
                                    InputField {
                                        max_lenght: 20;
                                        texto: "Quantidade Total: ";
                                        input <=> temp_estoque_quantidade_total;
                                    }


                                    VerticalBox {
                                        Text {
                                            text: "Medida";
                                            color: black;
                                        }
                        
                                        CustomComboBox {
                                            model: ["g", "mm", "un", "ml"];
                                            text-color: black;
                                            selected(current-value) => {
                                                temp_estoque_medida = current-value;
                                                debug(temp_estoque_medida)
                                            }
                                        }
                                    }

                                    InputField {
                                        max_lenght: 4;
                                        texto: "Preco: ";
                                        input <=> temp_estoque_preco;
                                    }

                                     
                                }

                                cor: white;
                            }
                        }
                    }
                }
            }

            GridBox {
                height: 90%;
                Row {
                    Container {
                        height: 50%;
                         
                        VerticalBox {
                    // spacing: Theme.spacing;
                    HorizontalBox {
                       
                        // spacing: Theme.spacing;
                        Text {
                                    text: "Material";
                                    color: Theme.onSurface;
                                    font-weight: 700;
                                    horizontal-alignment: center;
                                }

                                Text {
                                    text: "Preço";
                                    color: Theme.onSurface;
                                    font-weight: 700;
                                    horizontal-alignment: center;
                                }

                                Text {
                                    text: "Quantidade";
                                    color: Theme.onSurface;
                                    font-weight: 700;
                                    horizontal-alignment: center;
                                }
                            }
                        }

                        VerticalBox {
                            height: 80%;
                            ListView {
                                for estoque[index] in estoque_database: TouchArea {
                                    clicked => {
                                        root.selectec_estoque = root.estoque_database[index];
                                        Detalhes_Material.visible = true;
                                    }

                                      property <bool> selected_hover <=> self.has-hover;
                                    
                                    Rectangle {
                                        height: 90%;
                                        padding: 8px;
                                         background: !selected_hover? Theme.background:Theme.secondaryLight;
                                    // border-radius: 5px;
                                    // drop-shadow-offset-y: 1px;  
                                     
                                        HorizontalBox {
                                            alignment: center;
                                            Rectangle {
                                                width: 25%;
                                                Text {
                                                    text: estoque.material;
                                                    color: Theme.onSurface;
                                                    horizontal-alignment: center;
                                                    overflow: elide;
                                                }
                                            }

                                            Rectangle {
                                                width: 25%;
                                                Text {
                                                    text: "R$" + estoque.preco;
                                                    color: Theme.onSurface;
                                                    horizontal-alignment: center;
                                                }
                                            }

                                            Rectangle {
                                                width: 25%;
                                                Text {
                                                    text: estoque.quantidade + "/" + estoque.quantidade-total + estoque.medida;
                                                    color: Theme.onSurface;
                                                    horizontal-alignment: center;
                                                }
                                            }

                                            HorizontalBox {
                                                BaloButton {
                                                    width: 30px;
                                                    height: 20px;
                                                    texto: "+";
                                                    clicked => {
                                                        selectec_estoque = estoque;
                                                        estoque_quantidade = estoque.quantidade.to-float() + 1;
                                                        atualizar_estoque()
                                                    }
                                                }

                                                BaloButton {
                                                    width: 30px;
                                                    height: 20px;
                                                    texto: "-";
                                                    clicked => {
                                                        selectec_estoque = estoque;
                                                        estoque_quantidade = estoque.quantidade.to-float() - 1;
                                                        atualizar_estoque()
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }

                    VerticalBox {
                        Container {
                            height: 600px;
                            width: 30%;
                            cor: Theme.surface;
                            Detalhes_Material :=  VerticalBox {
                                visible: !selectec_estoque.id.is-empty;
                                HorizontalLayout {
                                    Text {
                                        vertical-alignment: center;
                                        text: "Detalhes de Material";
                                        color: black;
                                        font-size: Theme.fontSizeTitle;
                                        font-weight: 700;
                                    }

                                    HorizontalLayout {
                                        // visible: !selectec_estoque.id.is-empty;
                                        spacing: 10px;
                                        alignment: center;
                                        width: 3%;
                                        BaloButton {height: 30px; width: 50px; texto: "Editar"; clicked => {Edit_Estoque_Screen.show();}}
                                        BaloButton {background:#f01414;height: 30px; width: 50px; texto: "🗑️"; clicked => {excluir_estoque(); Detalhes_Material.visible=false}}
                                }
                                }
                                VerticalBox {
                                    
                                    Container {cor:white;
                                        height: 10%;
                                         VerticalLayout {
                                            Text {
                                               vertical-alignment: center;
                                                text: "Material:"; color: Theme.onSurface;
                                                font-size: 20px;
                                                font-weight: 700;
                                            }
                                            Text {
                                                vertical-alignment: center;
                                                text: selectec_estoque.material; color: Theme.onSurface;
                                                font-size: 20px;
                                                font-weight: 500;
                                            }
                                         }
                                         
                                    
                                    }

                                    Container {cor:white;
                                        height: 10%;
                                        VerticalLayout {
                                           Text {
                                            vertical-alignment: center;
                                               text: "Preço:"; color: Theme.onSurface;
                                               font-size: 20px;
                                               font-weight: 700;
                                           }
                                           Text {
                                            vertical-alignment: center;
                                               text: "R$"+selectec_estoque.preco; color:Theme.onSurface;
                                               font-size: 20px;
                                               font-weight: 500;
                                           }
                                        }
                                        
                                   
                                   }
                                   Container {cor:white;
                                    height: 10%;
                                    VerticalLayout {
                                       Text {
                                            vertical-alignment: center;
                                           text: "Quantidade:"; color: Theme.onSurface;
                                           font-size: 20px;
                                           font-weight: 700;
                                       }
                                       Text {
                                        vertical-alignment: center;
                                           text: selectec_estoque.quantidade+"/"+selectec_estoque.quantidade-total+selectec_estoque.medida; color: Theme.onSurface;
                                           font-size: 20px;
                                           font-weight: 500;
                                       }
                                    }
                                    
                               
                               }


                                    VerticalBox {
                                        alignment: end;
                                        Container {
                                            cor: Theme.surface;
                                            HorizontalBox {
                                                Text { color: Theme.onSurface; text: "Custo Total:"; font-size: 20px; font-weight: 700;}
                                                Text {
                                                    color: Theme.onSurface; 
                                                    text:preco_total_estoque+"R$";
                                                    font-size: 20px;
                                                    font-weight: 700;
                                                
                                                }
                                                
                                            }
                                        }
                                        

                                    }
                                    
                                    
                                    
                                }
                            }
                        }

                        HorizontalBox {
                            spacing: Theme.spacing;
                        }
                    }
                }
            }
        }
}

    novo_material := VerticalBox {
        visible: false;
      
        HorizontalBox {
            alignment: center;
            GridBox {
                width: 100%;
               
               

                Row { 
                    HorizontalBox {
                    alignment: center;
                    VerticalLayout {
                        alignment: center;
                        HorizontalBox {
                            alignment: center;
                            Text {
                                text: "Novo Material";
                                color: Theme.onSurface;
                                font-weight: 800;
                                font-size: 40px;
                            }
                        }
                        
                        Container {
                       
                           
                            VerticalBox {
                                InputField {
                                    max_lenght: 47;
                                    texto: "Nome do Material";
                                    input <=> root.estoque_material;
                                }
                    
                                InputField {
                                    max_lenght: 5;
                                    texto: "Quantidade";
                                    input <=> root.estoque_quantidade;
                                }
                    
                                VerticalBox {
                                    Text {
                                        text: "Medida";
                                        color: Theme.onSurface;
                                    }
                    
                                    CustomComboBox {
                                        model: ["g", "mm", "un", "ml"];
                                        text-color: Theme.onSurface;
                                        selected(current-value) => {
                                            estoque_medida = current-value;
                                            debug(estoque_medida)
                                        }
                                    }
                                }
                    
                                InputField {
                                    max_lenght: 5;
                                    texto: "Preço";
                                    input <=> root.estoque_preco_input;
                                }
                    
                                HorizontalBox {
                                    width: 50%;
                                    BaloButton {
                                        height: 5%;
                                        texto: "Voltar";
                                        clicked => {
                                            novo_material.visible = false;
                                            Estoques.visible = true;
                                        }
                                    }
                    
                                    BaloButton {
                                        height: 5%;
                                        texto: "Adicionar Material";
                                        clicked => {
                                            root.estoque_quantidade_total = estoque_quantidade;
                                            root.registrar_estoque();
                                            novo_material.visible = false;
                                            Estoques.visible = true;
                                        }
                                    }
                                }
                            }
                        }
                    }
                   
                }
                }
            }
        }
    }
}
 


    
   

