import { Theme } from "../styling.slint";
import { Container, SideButton, InputField, OverviewCard, BaloButton, CustomComboBox } from "../components.slint";
import { Button, ComboBox, LineEdit, VerticalBox, HorizontalBox, GridBox, ListView } from "std-widgets.slint";
import { Database, Impressoras, Estoque-Database } from "../shared.slint";

export component printer_screen {
    in-out property <[Impressoras]> impressoras_database;
    in-out property <string> input_modelo;
    in-out property <string> input_watts;
    in-out property <string> input_filamento;
    in-out property <string> input_tipo_filamento;
    in-out property <string> input_nozzle;
    in-out property <string> input_area_impressao;
    in-out property <int> filamento_total;
    in-out property <string> input_filamento_preco;
    in-out property <string> temp_modelo;
    in-out property <string> temp_watts;
    in-out property <string> temp_filamento;
    in-out property <string> temp_filamento_total;
    in-out property <string> temp_filamento_preco;
    in-out property <Impressoras> selected_impressora;

    in-out property <string> temp_nozzle;
    in-out property <string> temp_tipo_filamento;
    in-out property <string> temp_diametro;

    callback registrar_impressora();
    callback dashboard();
    callback estoque();
    callback configuracoes();
    callback pedidos();
    callback excluir_impressora();
    callback editar_impressora();

    Rectangle {
        width: parent.width;
        height: parent.height;
        background: Theme.background;

        Impressoras_Tela := VerticalBox {
            visible: true;

            HorizontalBox {
                spacing: Theme.spacing;
                alignment: start;

                Text {
                    vertical-alignment: center;
                    width: 81%;
                    text: "Impressoras";
                    color: Theme.onBackground;
                    font-weight: 800;
                    font-size: 40px;
                }

                BaloButton {
                    width: 150px;
                    height: 50px;
                    texto: "Adicionar Impressora";
                    background:!self.has-hover  ? Theme.primary : Theme.secondaryLight;
                    cor_texto: !self.has-hover ?  Theme.onPrimary :  Theme.onBackground;
                    clicked => {
                        nova_impressora.visible = true;
                        Impressoras_Tela.visible = false;
                    }
                }
            }

            HorizontalBox {
                VerticalLayout {
                    spacing: Theme.spacing;

                    GridBox {
                        Row {
                            HorizontalBox {
                                VerticalBox {
                                    Edit_Impressora_Screen := PopupWindow {
                                        width: parent.width;
                                        height: parent.height;
                                        close-policy: close-on-click-outside;
                                        x: parent.width / 2;
                                        y: parent.height / 50;

                                        VerticalLayout {
                                            Container {
                                                height: 50%;
                                                cor: Theme.background;
                                                width: 100%;
                                                shadow_blur: 10px;
                                                border_width: 1px;
                                                border_radius: 10px;

                                                VerticalBox {
                                                    HorizontalBox {
                                                        Text {
                                                            vertical-alignment: center;
                                                            text: "Editar Impressora";
                                                            color: Theme.onBackground;
                                                            font-weight: 800;
                                                            font-size: 20px;
                                                        }

                                                        BaloButton {
                                                            width: 80px;
                                                            height: 40px;
                                                            texto: "Confirmar";
                                                            clicked => {
                                                                editar_impressora();
                                                                Edit_Impressora_Screen.close();
                                                                
                                                            }
                                                        }
                                                    }
                                                    HorizontalBox {
                                                         spacing: Theme.spacing;
                                                         VerticalBox {
                                                             spacing: Theme.spacing;
                                                            
                                                            InputField {
                                                           
                                                                texto: "Modelo: ";
                                                                max_lenght: 40;
                                                                input <=> temp_modelo;
                                                            }

                                                            InputField {
                                                                
                                                                texto: "Watts: ";
                                                                max_lenght: 20;
                                                                input <=> temp_watts;
                                                            }

                                                            InputField {
                                                                 
                                                                max_lenght: 20;
                                                                texto: "Filamento: ";
                                                                input <=> temp_filamento;
                                                            }

                                                            InputField {
                                                                 
                                                                max_lenght: 20;
                                                                texto: "Filamento Total: ";
                                                                input <=> temp_filamento_total;
                                                            }

                                                        }
                                                        VerticalBox {
                                                              
                                                              InputField {
                                                                    max_lenght: 20;
                                                                    texto: "Preço do Filamento : ";
                                                                    input <=> temp_filamento_preco;
                                                                }
                                                                InputField {
                                                                    max_lenght: 20;
                                                                    texto: "Nozzle : ";
                                                                    input <=> temp_nozzle;
                                                                }
                                                                InputField {
                                                                    max_lenght: 60;
                                                                    texto: "Diametro : ";
                                                                    input <=> temp_diametro;
                                                                }
                                                                VerticalBox {
                                                                    Text {text: "Tipo de Filamento:"; color: Theme.onBackground;}

                                                                    CustomComboBox {
                                                                        model: ["PLA","ABS","PETG","Nylon"];
                                                                        current-value: temp_tipo_filamento;
                                                                        selected(current-value) => {
                                                                            temp_tipo_filamento= current-value;
                                                                                        
                                                                        }
                                                                    }

                                                                }
                                                        }
                                                    }
                                                  
                                                }
                                            }
                                        }
                                    }

                                    Container {
                                        cor: Theme.surface;
                                      

                                        VerticalBox {
                                            Text {
                                                text: "Total de Filamento";
                                                color: Theme.onSurface;
                                                font-weight: 800;
                                                font-size: 20px;
                                                horizontal-alignment: center;
                                            }

                                            Text {
                                                text: "\{root.filamento_total}g";
                                                color: Theme.onSurface;
                                                horizontal-alignment: center;
                                                font-weight: 700;
                                                font-size: 20px;
                                            }
                                        }
                                    }

                                    Container {
                                        cor: Theme.surface;
                                        
                                        Text {
                                            visible: selected_impressora.id.is-empty;
                                            Text {
                                                
                                                text: "Selecione uma Impressora!";
                                                color: Theme.onSurface;
                                                font-size: 25px;
                                            }
                                        }

                                       Detalhes_impressora := GridBox {
                                            visible: !selected_impressora.id.is-empty;

                                                Confirm_screen := PopupWindow{
                                                    width: parent.width;
                                                    height: parent.height /2 ;
                                                    close-policy: close-on-click-outside;
                                                    x: parent.width / 1.5;
                                                    y: parent.height * 0.2;
                                                    VerticalLayout {
                                                        
                                                        
                                                        Container {
                                                            cor: Theme.background;
                                                            width: 100%;
                                                            height: 100%;
                                                            shadow_blur: 10px;
                                                            border_width: 1px;
                                                            border_radius: 10px;
                                                            
                                                            VerticalBox {
                                                                HorizontalBox {
                                                                    Text {
                                                                    
                                                                        text: "Confirmação";
                                                                        color: Theme.onBackground;
                                                                        font-weight: 800;
                                                                        font-size: 20px;
                                                                    }
                                                                
                                                                }
                                                                HorizontalBox {
                                                                    
                                                                Text {
                                                                    
                                                                        text: "Deseja excluir o pedido de "+selected_impressora.modelo+" ?";
                                                                        color: Theme.onBackground;
                                                                        font-weight: 800;
                                                                        font-size: Theme.fontSizeBody;
                                                                    }
                                                                }
                                                                
                                                                HorizontalBox {
                                                                    spacing: Theme.spacing;
                                                                    BaloButton { width:80px; height: 40px;texto: "Cancelar"; clicked => {Confirm_screen.close()}}
                                                                    BaloButton { width:80px; height: 40px;texto: "Confirmar"; clicked => { excluir_impressora(); Confirm_screen.close();  }}
                                                                }
                                                                
                            
                                                            }
                                                        
                                                        }
                                                    }
                                    
                                                }



                                            Row {
                                                HorizontalBox {
                                                    spacing: Theme.spacing;
                                                    padding: Theme.spacing;

                                                    Text {
                                                        vertical-alignment: center;
                                                        color: Theme.onSurface;
                                                        text: selected_impressora.modelo;
                                                        font-size: 20px;
                                                        font-weight: 700;
                                                    }
                                                }

                                                HorizontalBox {
                                                    alignment: end;

                                                    BaloButton {
                                                        height: 30px;
                                                        width: 60px;
                                                        texto: "Editar";
                                                        clicked => {
                                                            Edit_Impressora_Screen.show();
                                                            temp_modelo = selected_impressora.modelo;
                                                            temp_filamento = selected_impressora.filamento;
                                                            temp_filamento_total = selected_impressora.filamento-total;
                                                            temp_nozzle = selected_impressora.nozzle;
                                                            temp_tipo_filamento = selected_impressora.filamento-tipo;
                                                            temp_watts = selected_impressora.watts;
                                                            temp_diametro = selected_impressora.diametro;
                                                            temp_filamento_preco = selected_impressora.filamento-preco;
                                                        }
                                                    }

                                                    BaloButton {
                                                        height: 30px;
                                                        width: 60px;
                                                        texto: "Excluir";
                                                        clicked => {
                                                           Confirm_screen.show();
                                                        }
                                                    }
                                                }
                                            }

                                            Row {
                                                Container {
                                                    cor: Theme.surface;
                                                    padding: Theme.spacing;
                                                    border_width: 0px;
                                                    shadow-color: transparent;

                                                    VerticalBox {
                                                        spacing: Theme.spacing;
                                                        padding: Theme.spacing;

                                                        Text {
                                                            horizontal-alignment: center;
                                                            color: Theme.onSurface;
                                                            text: "Filamento";
                                                            font-size: 20px;
                                                            font-weight: 700;
                                                        }
                                                    }

                                                    VerticalBox {
                                                        alignment: center;
                                                        spacing: Theme.spacing;
                                                        padding: Theme.spacing;

                                                        HorizontalBox {
                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: "Quantidade:";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }

                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: selected_impressora.filamento + "/" + selected_impressora.filamento-total + "g";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }
                                                        }

                                                        HorizontalBox {
                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: "Preço:";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }

                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: "R$" + selected_impressora.filamento-preco;
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }
                                                        }

                                                        HorizontalBox {
                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: "Tipo:";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }

                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: selected_impressora.filamento-tipo;
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }
                                                        }

                                                        HorizontalBox {
                                                            BaloButton {
                                                                texto: "Refill";

                                                                clicked => {
                                                                    temp_filamento = selected_impressora.filamento-total;
                                                                     editar_impressora();
                                                                     temp_filamento = "";
                                                                }
                                                            }
                                                        }
                                                    }
                                                }

                                                Container {
                                                    cor: Theme.surface;
                                                    padding: Theme.spacing;
                                                    border_width: 0px;
                                                    shadow-color: transparent;
                                                    VerticalBox {
                                                        spacing: Theme.spacing;
                                                        padding: Theme.spacing;

                                                        Text {
                                                            horizontal-alignment: center;
                                                            color: Theme.onSurface;
                                                            text: "Detalhes";
                                                            font-size: 20px;
                                                            font-weight: 700;
                                                        }
                                                    }

                                                    width: 50%;

                                                    VerticalBox {
                                                        spacing: Theme.spacing;
                                                        padding: Theme.spacing;
                                                        alignment: center;

                                                        HorizontalBox {
                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: "Nozzle[mm]:";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }

                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: selected_impressora.nozzle;
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }
                                                        }

                                                        HorizontalBox {
                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: "Watts[W]:";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }

                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: selected_impressora.watts + "W";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }
                                                        }

                                                        HorizontalBox {
                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: "Diametro:";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }

                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: Theme.onSurface;
                                                                text: selected_impressora.diametro;
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }
                                                        }
                                                    }
                                                }
                                            }

                                            Row { }
                                        }
                                    }
                                }
                            }

                            VerticalBox {
                                HorizontalBox {
                                    Container {
                                        cor: Theme.surface;

                                        VerticalBox {
                                            HorizontalBox {
                                                Text {
                                                    text: "Modelo";
                                                    color: Theme.onSurface;
                                                    font-weight: 700;
                                                    horizontal-alignment: center;
                                                }

                                                Text {
                                                    text: "Filamento";
                                                    color: Theme.onSurface;
                                                    font-weight: 700;
                                                    horizontal-alignment: center;
                                                }
                                            }

                                            for printer[index] in impressoras_database: TouchArea {
                                                clicked => {
                                                    selected_impressora = impressoras_database[index];
                                                }
                                                property <bool> selected_hover <=> self.has-hover;

                                               
                                                    Rectangle {
                                                    max-height: 10px;
                                                    border-radius: 5px;
                                                    background: !selected_hover && selected_impressora.id != printer.id? Theme.background:Theme.secondaryLight;

                                                        HorizontalBox {
                                                            Text {
                                                                text: printer.modelo;
                                                                color: Theme.onSurface;
                                                                horizontal-alignment: center;
                                                            }

                                                            Text {
                                                                text: printer.filamento;
                                                                color: Theme.onSurface;
                                                                horizontal-alignment: center;
                                                            }
                                                        }
                                                    }
                                                
                                              
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        nova_impressora := Rectangle {
            width: 100%;
            height: 100%;
            background: Theme.background;
            visible: false;

            VerticalBox {
                HorizontalBox {
                    Text {
                        vertical-alignment: center;
                        text: "Adicionar Impressora";
                        color: Theme.onBackground;
                        font-weight: 800;
                        font-size: 40px;
                    }
                }

                GridBox {
                    spacing: Theme.spacing;

                    Row {
                        Container {
                             
                            height: 50%;
                            cor: Theme.surface;
                            

                            VerticalBox {
                                  Text {
                                    vertical-alignment: center;
                                    text: "Impressora";
                                    color: Theme.onSurface;
                                    font-weight: 700;
                                    font-size: 20px;
                                }   
                                InputField {
                                    max_lenght: 60;
                                    texto: "Modelo de Impressora";
                                    input <=> root.input_modelo;
                                }

                                InputField {
                                    max_lenght: 5;
                                    texto: "Watts [W]";
                                    input <=> root.input_watts;
                                }

                                InputField {
                                    max_lenght: 5;
                                    texto: "Nozzle [mm]";
                                    input <=> root.input_nozzle;
                                }

                                InputField {
                                    max_lenght: 40;
                                    texto: "Diametro";
                                    input <=> root.input_area_impressao;
                                }


                              

                                HorizontalBox {
                                    width: 50%;

                                    BaloButton {
                                        height: 5%;
                                        texto: "Voltar";
                                        clicked => {
                                            nova_impressora.visible = false;
                                            Impressoras_Tela.visible = true;
                                        }
                                    }

                                   
                                }
                            }
                        }

                        Container { 
                            
                             
                            cor: Theme.surface;
                            HorizontalLayout {
                                alignment: center;
                                    VerticalBox {
                                  Text {
                                    vertical-alignment: center;
                                    text: "Filamento";
                                    color: Theme.onSurface;
                                    font-weight: 700;
                                    font-size: 20px;
                                }   

                                  InputField {
                                    max_lenght: 5;
                                    texto: "Quantidade de filamento [g]";
                                    input <=> root.input_filamento;
                                }

                                InputField {
                                    max_lenght: 5;
                                    texto: "Preço do Filamento [R$]";
                                    input <=> root.input_filamento_preco;
                                }

                              

                                    CustomComboBox {
                                        texto: "Tipo de Filamento";
                                        model: ["PLA","ABS","PETG","Nylon"];
                                        selected(current-value) => {
                                            input_tipo_filamento = current-value;
                                                         
                                        }
                                    }

                                
                                  
                                  InputField {
                                    visible: false;
                                   
                                }
                                HorizontalBox {
                                     BaloButton {
                                        height: 5%;
                                        texto: "Adicionar Impressora";
                                        clicked => {
                                            root.registrar_impressora();
                                            nova_impressora.visible = false;
                                            Impressoras_Tela.visible = true;
                                        }
                                    }
                                }
                            }
                            }
                        
                            

                        }
                    }
                }
            }
        }
    }
}
