import { Theme } from "../styling.slint";
import { Container, SideButton, InputField, OverviewCard, BaloButton } from "../components.slint";
import {
    Button, ComboBox, LineEdit,
    VerticalBox, HorizontalBox, GridBox, ListView
} from "std-widgets.slint";

import { Database, Impressoras, Estoque-Database } from "../shared.slint";


export component printer_screen {
    in-out property <[Impressoras]> impressoras_database;
    in-out property <string> input_modelo;
    in-out property <string> input_watts;
    in-out property <string> input_filamento;
    in-out property <int> filamento_total;
    in-out property <string> input_filamento_preco;

    in-out property <string> temp_modelo;
    in-out property <string> temp_watts;
    in-out property <string> temp_filamento;
    in-out property <string> temp_filamento_total;
    in-out property <string> temp_filamento_preco;

    in-out property <Impressoras> selected_impressora;
    callback registrar_impressora();
    callback dashboard();
    callback estoque();
    callback configuracoes();
    callback pedidos();
    callback excluir_impressora();
    callback editar_impressora();
Container {
    width: parent.width;
    height: parent.height;
    cor: white;
    Impressoras_Tela := VerticalBox {
        //  height: 700px;
        //  width: 900px;
        visible: true;
        // spacing: Theme.spacing; 
        HorizontalBox {
            spacing: Theme.spacing;
            alignment: start;
            // max-height: 50px;
            Text {
                vertical-alignment: center;
                width: 81%;
                text: "Impressoras";
                color: black;
                font-weight: 800;
                font-size: 40px;
            }
           
            BaloButton {
                
                width: 150px;
                height: 50px;
                texto: "Adicionar Impressora";
                clicked => {
                    nova_impressora.visible = true;
                    Impressoras_Tela.visible = false;
                }
                 
            }
        }
    

    
     HorizontalBox {
            // spacing: Theme.spacing;
    
            VerticalLayout {
                spacing: Theme.spacing;
        
               

                GridBox {
                    Row {                       
                        HorizontalBox {
                            VerticalBox {
                                Edit_Impressora_Screen := PopupWindow {
                                    width: parent.width;
                                    height: parent.height;
                                    close-policy: close-on-click-outside;
                                    x: parent.width / 2;
                                    y: parent.height / 50;
                                    VerticalLayout {
                                        // width: 500px;
                                        // height: 500px;
                                        Container {
                                            height: 50%;
                                            cor: white;
                                            width: 100%;
                                            // height: 100%;
                                            shadow_blur: 10px;
                                            border_width: 1px;
                                            border_radius: 10px;
                                            VerticalBox {
                                               
                                              
                                                HorizontalBox {
                                                    Text {
                                                        vertical-alignment: center;
                                                        text: "Editar Impressora";
                                                        color: black;
                                                        font-weight: 800;
                                                        font-size: 20px;
                                                    }
                        
                                                    BaloButton {
                                                        width: 80px;
                                                        height: 40px;
                                                        texto: "Confirmar";
                                                        clicked => {
                                                            
                                                            editar_impressora();
                                                            Edit_Impressora_Screen.close();
                                                            temp_filamento ="";
                                                            temp_watts = "";
                                                            temp_modelo = "";
                                                            temp_filamento_total = "";
                                                            temp_filamento_preco = "";
                                                        }
                                                    }
                                                }
                        
                                                InputField {
                                                    texto: "Modelo: ";
                                                    max_lenght: 40;
                                                    input <=> temp_modelo;
                                                    
                                                }
                        
                                                InputField {
                                                    texto: "Watts: ";
                                                    max_lenght: 20;
                                                    input <=> temp_watts;
                                                    
                                                }
                                                InputField {
                                                    max_lenght: 20;
                                                    texto: "Filamento: ";
                                                    input <=> temp_filamento;
                                                    
                                                }
                                                InputField {
                                                    max_lenght: 20;
                                                    texto: "Filamento Total: ";
                                                    input <=> temp_filamento_total;
                                                    
                                                }
                                                InputField {
                                                    max_lenght: 20;
                                                    texto: "Preço do Filamento : ";
                                                    input <=> temp_filamento_preco;
                                                    
                                                }
                        
                        
                                                
                        
                         
                                        }
                                    }
                                }
                            }
                                // spacing: Theme.spacing;
    
                                HorizontalBox {
                                    // spacing: Theme.spacing;

                                    Container {
                                        cor: white;
                                        width: 20%;
                                        height: 20%;
                                        VerticalBox {
                                            Text {
                                                text: "Total de Filamento";
                                                color: black;
                                                font-weight: 800;
                                                font-size: 20px;
                                                horizontal-alignment: center;
                                            }

                                            Text {
                                                text: "\{root.filamento_total}g";
                                                color: black;
                                                horizontal-alignment: center;
                                                font-weight: 700;
                                                font-size: 20px;
                                            }
                                        }
                                    }
                                }

                                Container {


                                   
                                
                                    cor: white;
                                    GridBox {
                                       
                                        Row { 

                                            VerticalLayout {
                                                HorizontalBox {
                                                    Text {
                                                        vertical-alignment: center;
                                                        horizontal-alignment: center;
                                                        color:black;
                                                        text: selected_impressora.modelo;
                                                        font-size: 20px;
                                                        font-weight: 600;
                                                    }
                                                    BaloButton { width: 10%; texto: "Editar"; clicked => {Edit_Impressora_Screen.show();}}
                                                    BaloButton {width: 10%; texto: "Excluir"; clicked => {excluir_impressora()}}

                                                }
                                               
                                            }


                                        }

                                        Row {
                                            
                                            GridBox {
                                                Row{
                                                    Container {cor:white;
                                                     
                                                        width: 30%;
                                                        height: 30%;
                                                    VerticalBox {
                                                      
                                                        Text {
                                                            horizontal-alignment: center;
                                                            color: black;
                                                            text: "Filamento";
                                                            font-size: 15px;
                                                            font-weight: 600;
                                                        }
                                                        Text {
                                                            horizontal-alignment: center;
                                                            color:black;
                                                            text:selected_impressora.filamento+"/"+selected_impressora.filamento-total+"g";
                                                            font-size: 15px;
                                                            font-weight: 600;

                                                        }
                                                        Text {
                                                            horizontal-alignment: center;
                                                            color: black;
                                                            text: "Preço";
                                                            font-size: 15px;
                                                            font-weight: 600;
                                                        }
                                                        Text {
                                                            horizontal-alignment: center;
                                                            color:black;
                                                            text:selected_impressora.filamento-preco+ "R$";
                                                            font-size: 15px;
                                                            font-weight: 600;

                                                        }

                                                    }
                                                    
                                                    
                                                    }
                                                    Container {cor:white;
                                                    
                                                        VerticalBox {
                                                      
                                                            Text {
                                                                horizontal-alignment: center;
                                                                color: black;
                                                                text: "Watts";
                                                                font-size: 15px;
                                                                font-weight: 600;
                                                            }
                                                            Text {
                                                                horizontal-alignment: center;
                                                                color:black;
                                                                text: selected_impressora.watts;
                                                                font-size: 15px;
                                                                font-weight: 600;
    
                                                            }
    
                                                        }
                                                    
                                                    }
                                                }
                                                Row{
                                                    Container {cor:white;}
                                                    Container {cor:white;}
                                                }
                                            }



                                        }
                                    }
                                }
                            }
                        }

                        VerticalBox {
                            // spacing: Theme.spacing;
    
                            HorizontalBox {
                                // spacing: Theme.spacing;
    
                                Container {
                                    cor: white;
                                    VerticalBox {
                                        // spacing: Theme.spacing;
    
                                        HorizontalBox {
                                            // spacing: Theme.spacing;
                                            Text {
                                                text: "Modelo";
                                                color: black;
                                                font-weight: 700;
                                                horizontal-alignment: center;
                                            }

                                            Text {
                                                text: "Filamento";
                                                color: black;
                                                font-weight: 700;
                                                horizontal-alignment: center;
                                            }
                                        }

                                        for printer[index] in impressoras_database: TouchArea {
                                             
                                            clicked => {

                                                selected_impressora = impressoras_database[index];

                                            }
                                            // spacing: Theme.spacing;
                                            // padding: Theme.spacing;
                                            Rectangle {
                                                max-height: 10px;
                                                // padding: Theme.spacing;
                                                border-radius: 5px;
                                                background: rgba(0,0,0,0.05);
                                                HorizontalBox {
                                                    Text {
                                                        text: printer.modelo;
                                                        color: black;
                                                        horizontal-alignment: center;
                                                    }

                                                    Text {
                                                        text: printer.filamento;
                                                        color: black;
                                                        horizontal-alignment: center;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }

    nova_impressora := Rectangle {
        width: 100%;
        height: 100%;
        background: white;
        visible: false;
        HorizontalBox {
            // spacing: Theme.spacing;
    
            VerticalBox {
                // spacing: Theme.spacing;
    
                 

                GridBox {
                    // spacing: Theme.spacing;
     
    
                    Row {
                        HorizontalBox {
                            
                            // spacing: Theme.spacing;
    
                            VerticalBox {
                                HorizontalBox {
                                    alignment: center;
                                    Text {
                                        vertical-alignment: center;
                                        text: "Adicionar Impressora";
                                        color: black;
                                        font-weight: 800;
                                        font-size: 40px;
                                    }

                                }
                                
                                // spacing: Theme.spacing;
                                alignment: center;
                                HorizontalBox {
                                    // spacing: Theme.spacing;
                                    
                                alignment: center;
                                    Container {
                                        width: 50%;
                                        height: 50%;
                                        cor: white;
                                        VerticalBox {
                                            InputField {
                                                max_lenght: 47;
                                                texto: "Modelo de Impressora";
                                                input <=> root.input_modelo;
                                            }

                                            InputField {
                                                max_lenght: 5;
                                                texto: "Watts [W]";
                                                input <=> root.input_watts;
                                            }

                                            InputField {
                                                max_lenght: 5;
                                                texto: "Filamento [g]";
                                                input <=> root.input_filamento;
                                            }
                                            InputField {
                                                max_lenght: 5;
                                                texto: "Preço do Filamento [R$]";
                                                input <=> root.input_filamento_preco;
                                            }

                                            
                                            HorizontalBox {
                                                width: 50%;
                                                BaloButton {
                                                     
                                                    height: 5%;
                                                    texto: "Voltar";
                                                    clicked => {
                                                        nova_impressora.visible = false;
                                                        Impressoras_Tela.visible = true;
                                                    }
                                                }
                                                BaloButton {
                                                     
                                                    height: 5%;
                                                    texto: "Adicionar Impressora";
                                                    clicked => {
                                                        root.registrar_impressora();
                                                        nova_impressora.visible = false;
                                                        Impressoras_Tela.visible = true;
                                                    }
                                                }
                                                

                                            }
                                           
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
    
}
