import { Theme } from "../styling.slint";
import { Container, SideButton, InputField, OverviewCard, BaloButton, CustomComboBox, DataInput } from "../components.slint";
import { Button, ComboBox, LineEdit, VerticalBox, HorizontalBox, GridBox, ListView, ScrollView, DatePickerPopup } from "std-widgets.slint";

import { Database, Impressoras, Estoque-Database } from "../shared.slint";

export component calculator_screen {
    in-out property <string> filamento;
    in-out property <string> material;
    in-out property <string> tempo;
    in-out property <string> energia;
    in-out property <string> lucro;
    in-out property <float> total;
    in-out property <string> nome_cliente;
    in-out property <string> endereco;
    in-out property <string> entrega;
    in-out property <[string]> impressoras_string;
    in-out property <string> combobox_selected;
    in-out property <[Database]> clients_database;
    in-out property <int> filamento_printer;
    in-out property <string> observacao;
    in-out property <string> modelo;
    in-out property <string> status;
    in-out property <Database> selected_client;

    callback calcular_preco();
    callback registrar_cliente();
    callback resetar_inputs();
    callback atualizar_filamento();
    callback editar_cliente();
    callback excluir_cliente();
    callback atualizar_f_preco();

    callback estoque();
    callback impressoras();
    callback dashboard();
    callback configuracoes();

    // Temporary Variables for Editing
    in-out property <string> temp_nome_client;
    in-out property <string> temp_entrega;
    in-out property <string> temp_endereco;
    in-out property <string> temp_observacao;
    in-out property <string> temp_status;

    width: 600px;
    height: 600px;
    Container {
        width: parent.width;
        height: parent.height;
        cor: #f9f9f9; // Light background for better contrast
        visible: true;

        Pedidos := VerticalBox {
            spacing: 16px;
            padding: 16px;

            HorizontalBox {
                spacing: 16px;
                alignment: center;

                Text {
                    text: "Pedidos";
                    color: #333333;
                    font-weight: 800;
                    font-size: 36px;
                }

                BaloButton {
                    width: 150px;
                    height: 50px;
                    texto: "Adicionar Pedido";
                    background: #4CAF50; // Green button
                    
                    // clicked => { Novo_Pedido.visible = true; Pedidos.visible = false; }
                }

                BaloButton {
                    width: 150px;
                    height: 50px;
                    texto: "Dashboard";
                    background: #2196F3; // Blue button
                     
                    clicked => { dashboard(); }
                }

                BaloButton {
                    width: 150px;
                    height: 50px;
                    texto: "Estoque";
                    background: #FF9800; // Orange button
                    
                    clicked => { estoque(); }
                }

                BaloButton {
                    width: 150px;
                    height: 50px;
                    texto: "Impressoras";
                    background: #9C27B0; // Purple button
                     
                    clicked => { impressoras(); }
                }

                BaloButton {
                    width: 150px;
                    height: 50px;
                    texto: "Configurações";
                    background: #607D8B; // Gray button
                    
                    clicked => { configuracoes(); }
                }
            }

            GridBox {
                spacing: 16px;
                padding: 16px;

                Row {
                    Container {
                        cor: white;
                        border-radius: 8px;
                        shadow_blur: 4px;
                        padding: 16px;

                        VerticalBox {
                            spacing: 8px;

                            InputField {
                                texto: "Pesquisar";
                                place_holder: "Digite o nome do cliente...";
                                 
                            }

                            HorizontalBox {
                                spacing: 16px;

                                Text {
                                    text: "Nome";
                                    color: #333333;
                                    font-weight: 700;
                                    horizontal-alignment: center;
                                }

                                Text {
                                    text: "Data de Entrega";
                                    color: #333333;
                                    font-weight: 700;
                                    horizontal-alignment: center;
                                }

                                Text {
                                    text: "Status";
                                    color: #333333;
                                    font-weight: 700;
                                    horizontal-alignment: center;
                                }

                                Text {
                                    text: "Preço";
                                    color: #333333;
                                    font-weight: 700;
                                    horizontal-alignment: center;
                                }
                            }
                        }
                    }
                }

                Row {
                    ListView {
                        height: 85%;
                    
                        for client[index] in clients_database: TouchArea {
                            clicked => {
                                root.selected_client = root.clients_database[index];
                                // Detalhes_Pedido.visible = true;
                            }

                            Rectangle {
                                height: 90%;
                                padding: 8px;
                                border-radius: 8px;
                                background: rgba(0.5, 0, 1, 0.1);
                                 

                                HorizontalBox {
                                    alignment: center;

                                    Rectangle {
                                        width: 25%;
                                        Text {
                                            text: client.nome;
                                            color: #333333;
                                            horizontal-alignment: center;
                                            overflow: elide;
                                        }
                                    }

                                    Rectangle {
                                        width: 25%;
                                        Text {
                                            text: client.entrega;
                                            color: #333333;
                                            horizontal-alignment: center;
                                        }
                                    }

                                    Rectangle {
                                        width: 25%;
                                        Text {
                                            text: client.status;
                                            color: #333333;
                                            horizontal-alignment: center;
                                        }
                                    }

                                    Rectangle {
                                        width: 25%;
                                        Text {
                                            text: "R$" + client.preco.to-fixed(2);
                                            color: #333333;
                                            horizontal-alignment: center;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
