import { Theme } from "../styling.slint";
import { Container, SideButton, InputField, OverviewCard, BaloButton, CustomComboBox } from "../components.slint";
import {
    Button, ComboBox, LineEdit,
    VerticalBox, HorizontalBox, GridBox, ListView, TabWidget
} from "std-widgets.slint";

import { Database, Impressoras, Estoque-Database } from "../shared.slint";



export component settings_screen {

    in-out property <string> settings_energia;
    in-out property <string> settings_lucro;
    in-out property <string> tema : "Light";

    callback registrar_settings();
    callback dashboard();
    callback carregar_tema();
    Rectangle {
        clip: true;
        background:Theme.background;
        width: parent.width;
        height: parent.height;
        settings_screen := VerticalBox {
        
            // alignment: center;
            HorizontalBox {
     
                    
                    
                     
                    VerticalLayout {
                        spacing: Theme.spacing;
                        padding: Theme.spacing;
                        
                        HorizontalLayout {
    
                            height: 5%;
                            // width: 5%;
                            spacing: Theme.spacing;
                            padding: Theme.spacing;
                            Text {
                                height: 10%;
                                text: "Configurações";
                                color: Theme.onBackground;
                                font-size: 40px;
                                font-weight: 800;
                            }
                            BaloButton {texto: "Voltar";clicked => {dashboard();}
                                background:!self.has-hover  ? Theme.primary : Theme.secondaryLight;
                                cor_texto: !self.has-hover ?  Theme.onPrimary :  Theme.onBackground;
                            }
                            BaloButton {texto: "Confirmar";clicked => {registrar_settings(); dashboard();}
                                background:!self.has-hover  ? Theme.primary : Theme.secondaryLight;
                                cor_texto: !self.has-hover ?  Theme.onPrimary :  Theme.onBackground;
                            }
                             
     
                        }

                        GridLayout {
                            spacing: Theme.spacing;
                            padding: Theme.spacing;
                            Row {
                                
                                   Container {
                                    width: 50%;
                                    padding: Theme.spacing;
                                    
                                    cor: Theme.surface;
                                    VerticalBox {



                                        InputField {
                                                    input <=> settings_energia;
                                                    texto: "Taxa de Energia";
                                                }
                        
                                                InputField {
                                                    texto: "Lucro padrão:";
                                                    input <=> settings_lucro;
                                                }
                                    }
                                    }   
                                    Container {
                                        width: 50%;
                                        cor:Theme.surface;

                                        CustomComboBox {
                                                        model: ["Light","Dark","TealSunsetLight","TealSunsetDark","PastelDreamLight","PastelDreamDark"];
                                                        texto: "Tema";
                                                        current-value: tema;
                                                        selected (current-value) => {
                                                            tema = current-value;
                                                                carregar_tema();
                                                        }
                                                    
                                                    }
                                    }      
                                    

                            }

                            Row{
                                     
                                    Container {
                                        
                                        VerticalLayout {

                                            HorizontalLayout {
                                                 
                                                    VerticalLayout {
                                                        width: 50%;
                                                        InputField {
                                                        texto: "Nome da Loja:";
                                                        input <=> settings_lucro;
                                                    }
                                                    InputField {
                                                        texto: "Cpf:";
                                                        input <=> settings_lucro;
                                                    }
                                                    
                                                    InputField {
                                                        texto: "Endereço:";
                                                        input <=> settings_lucro;
                                                    }
                                                    
                                                      InputField {
                                                        texto: "Numero:";
                                                        input <=> settings_lucro;
                                                    }
                                                   

                                                }

                                              
                                                VerticalLayout {
                                                    width: 50%;
                                                     InputField {
                                                        texto: "Bairo:";
                                                        input <=> settings_lucro;
                                                    }
                                                      InputField {
                                                        texto: "Cidade:";
                                                        input <=> settings_lucro;
                                                    }
                                                    InputField {
                                                        texto: "Cep:";
                                                        input <=> settings_lucro;
                                                    }
                                                    InputField {
                                                        texto: "Estado:";
                                                        input <=> settings_lucro;
                                                    }
                                                }
                                            
                                            
                                            }
                                                    
                                            
                                        }


                                    }
                                }
                                }
                               
                    
                    }
                }
            }
        }
}
   

