import { Theme } from "styling.slint";
import { Container, SideButton, InputField, OverviewCard,CustomComboBox} from "components.slint";
import {Button, ComboBox, LineEdit,VerticalBox, HorizontalBox, GridBox, ListView,StyleMetrics} from "std-widgets.slint";
import { dashboard_screen } from "screens/dashboard.slint";
import { calculator_screen } from "screens/product_calculator.slint";
import { estoque_screen} from "screens/estoque.slint";
import { Database, Impressoras, Estoque-Database } from "shared.slint";
import { printer-screen } from "screens/printer.slint";
import {settings_screen} from "screens/settings.slint";

export component AppWindow inherits Window {
    function activate(i: int) {
        Calculator_Screen.visible = (i == 1);
        Estoque_Screen.visible = (i == 2);
        Printer_Screen.visible = (i == 3);
        Settings_Screen.visible = (i == 4);
        Dashboard_Screen.visible = (i == 5);
    }
    in-out property <string> filamento;
    in-out property <string> material;
    in-out property <string> tempo;
    in-out property <string> energia;
    in-out property <string> lucro;
    in-out property <float> total;
    in-out property <string> nome_cliente;
    in-out property <string> endereco;
    in-out property <string> entrega;
    in-out property <string> observacao;
    in-out property <string> modelo;
    in-out property <string> input_modelo;
    in-out property <string> input_watts;
    in-out property <[Impressoras]> impressoras;
    in-out property <[string]> impressoras_string;
    in-out property <[Database]> clients_database;
    in-out property <[Estoque-Database]> estoque_database;
    in-out property <string> estoque_material;
    in-out property <string> estoque_quantidade;
    in-out property <string> estoque_quantidade_total;
    in-out property <string> estoque_medida;
    in-out property <float> vendas_total;
    in-out property <string> combobox_selected;
    in-out property <string> status;
    in-out property <Database> selected_client;
    in-out property <int> filamento_total;
    in-out property <string> filamento_printer;
    in-out property <string> temp_nome_client;
    in-out property <string> temp_entrega;
    in-out property <string> temp_endereco;
    in-out property <string> temp_observacao;
    in-out property <string> estoque_preco_input;
    in-out property <string> settings_lucro;
    in-out property <string> settings_energia;
    in-out property <Estoque-Database> selectec_estoque;
    in-out property <int> preco_total_estoque;

    in-out property <string> temp_estoque_material;
    in-out property <string> temp_estoque_quantidade;
    in-out property <string> temp_estoque_quantidade_total;
    in-out property <string> temp_estoque_preco;
    in-out property <string> temp_estoque_medida;
    in-out property <string> temp_status;


    callback calcular_preco();
    callback registrar_cliente();
    callback registrar_impressora();
    callback registrar_estoque();
    callback atualizar_filamento();
    callback editar_cliente();
    callback excluir_cliente();
    callback formater_date();
    callback registrar_settings();
    callback atualizar_estoque();
    callback estoque_total_preco();
    callback excluir_estoque();

    no-frame: false;
    width: 1280px;
    combobox-selected: "Teste";
    full-screen: false;
    height: 820px;
    HorizontalBox {
        spacing: Theme.spacing;
        padding: Theme.spacing;
        width: parent.width;
        x: 4px;
        y: 5px;
        height: parent.height;
      
        /* --- SIDEBAR --- */
        // VerticalBox {
        //     width: 15%;
        //     spacing: Theme.spacing;
        //     padding: Theme.spacing;
        //     SideButton {
        //         texto: "Tela 1";
        //         clicked => {
        //             activate(1)
        //         }
        //     }

        //     SideButton {
        //         texto: "Tela 2";
        //         clicked => {
        //             activate(2)
        //         }
        //     }

        //     SideButton {
        //         texto: "Tela 3";
        //         clicked => {
        //             activate(3)
        //         }
        //     }

        //     SideButton {
        //         texto: "Tela 4";
        //         clicked => {
        //             activate(4)
        //         }
        //     }

        //     SideButton {
        //         texto: "Tela 5";
        //         clicked => {
        //             activate(5)
        //         }
        //     }
        // }

        /* --- CONTEÚDO PRINCIPAL --- */
        Rectangle {
            background: Theme.background;
            padding: Theme.spacing;
            border-radius: 20px;
            clip: true;
            visible: true;
            Calculator_Screen := calculator-screen {
                width: parent.width;
                height: parent.height;
                visible: false;
                filamento <=> filamento;
                material <=> material;
                tempo <=> tempo;
                energia <=> energia;
                lucro <=> lucro;
                total <=> total;
                nome_cliente <=> nome_cliente;
                endereco <=> endereco;
                entrega <=> entrega;
                clients_database <=> clients_database;
                impressoras_string <=> impressoras_string;
                combobox_selected <=> combobox_selected;
                selected_client <=> selected_client;
                modelo <=> modelo;
                observacao <=> observacao;
                status <=> status;
                temp_nome_client <=> temp_nome_client;
                temp_entrega <=> temp_entrega;
                temp_endereco <=> temp_endereco;
                temp_observacao <=> temp_observacao;
                temp_status <=> temp_status;
                registrar_cliente => {
                    root.registrar_cliente();
                }
                calcular_preco => {
                    root.calcular_preco();
                }
                atualizar_filamento => {
                    root.atualizar_filamento();
                }
                resetar_inputs => {
                    observacao = "";
                    modelo = "";
                    nome_cliente = "";
                    tempo = "";
                    energia = settings_energia;
                    lucro = settings_lucro;
                    total = 0;
                    endereco = "";
                    entrega = "";
                    combobox_selected = "";
                    filamento = 0;
                    material = 0;
                }
                editar_cliente => {
                    root.editar_cliente();
                }
                excluir_cliente => {
                    root.excluir_cliente();
                }
                dashboard => {
                    activate(5);
                }
                impressoras => {
                    activate(3);
                }
                estoque => {
                    activate(2);
                }
                configuracoes => {
                    activate(4);
                }
            }

            Estoque_Screen := estoque-screen {
                width: parent.width;
                height: parent.height;
                visible: true;
                estoque_database <=> estoque_database;
                estoque_material <=> estoque_material;
                estoque_quantidade <=> estoque_quantidade;
                estoque_quantidade_total <=> estoque_quantidade_total;
                estoque_medida <=> estoque_medida;
                estoque_preco_input <=> estoque_preco_input;
                selectec_estoque <=> selectec_estoque;
                preco_total_estoque <=>preco_total_estoque ;


                temp_estoque_material <=> temp_estoque_material;
                temp_estoque_quantidade <=> temp_estoque_quantidade;
                temp_estoque_quantidade_total <=> temp_estoque_quantidade_total;
                temp_estoque_preco <=>temp_estoque_preco;
                temp_estoque_medida <=> temp_estoque_medida;
                registrar_estoque => {
                    registrar_estoque();
                }
                dashboard => {
                    activate(5);
                }
                impressoras => {
                    activate(3);
                }
                estoque => {
                    activate(2);
                }
                configuracoes => {
                    activate(4);
                }
                pedidos => {
                    activate(1);
                }
                atualizar_estoque => {
                    atualizar_estoque();
                }
                estoque_total_preco => {
                    estoque_total_preco();
                }
                excluir_estoque => {
                    excluir_estoque();
                }
            }

            Printer_Screen := printer-screen {
                visible: false;
                width: parent.width;
                height: parent.height;
                input_modelo <=> input_modelo;
                input_watts <=> input_watts;
                input_filamento <=> filamento_printer;
                impressoras_database <=> impressoras;
                filamento_total <=> filamento_total;
                registrar_impressora => {
                    root.registrar_impressora();
                }
                dashboard => {
                    activate(5);
                }
                estoque => {
                    activate(2);
                }
                configuracoes => {
                    activate(4);
                }
                pedidos => {
                    activate(1);
                }
            }

            Dashboard_Screen := dashboard-screen {
                visible: false;
                width: parent.width;
                height: parent.height;
                clients_database <=> clients_database;
                vendas_total <=> vendas_total;
                selected_client <=> selected_client;
                pedidos => {
                    activate(1);
                }
                estoque => {
                    activate(2);
                }
                impressoras => {
                    activate(3);
                }
                configuracoes => {
                    activate(4);
                }
            }

            Settings-Screen := settings-screen {
                width: parent.width;
                height: parent.height;
                visible: false;
                settings_lucro <=> settings_lucro;
                settings_energia <=> settings_energia;
                registrar_settings => {
                    registrar_settings();
                }
                dashboard => {
                    activate(5);
                }
            }
        }
    }
}
