export struct Settings {
    energia:float,
    taxa:int,
}


export struct Database {
    id:string,
    nome: string,
    endereco: string,
    entrega: string,
    preco: float,
    observacao: string,
    modelo: string,
    status: string,
}

export struct Estoque_Database {
    id:string,
    material: string,
    quantidade: string,
    quantidade_total: int,
    medida: string,
    preco: string,
}

export struct Impressoras {
    modelo: string,
    watts: string,
    filamento: int,
}
