export struct Settings {
    energia:float,
    taxa:int,
    tema:string,
}


export struct Database {
    id:string,
    nome: string,
    endereco: string,
    entrega: string,
    preco: float,
    observacao: string,
    modelo: string,
    status: string,
    filamento_gasto:string,
    data_criacao:string,
    cep:string,
    telefone:string,
    cpf:string,
}

export struct Estoque_Database {
    id:string,
    material: string,
    quantidade: string,
    quantidade_total: int,
    medida: string,
    preco: string,
}

export struct Impressoras {
    id: string,
    modelo: string,
    watts: string,
    filamento: int,
    filamento_total: int,
    filamento_preco:int,
    filamento_tipo:string,
    nozzle:string,
    diametro:string,
}
